### ISSUE TITLE
Dataset is not available

### ISSUE THREAD

**Issue by xml94** [haiyang-qian/code-and-dataset#1]
Hello,

Thank you for your interesting work and shared codes with dataset.

I try to check the dataset, but currently it is not available.

Could you please fix it?

Thank you inadvance.

**Comment by haiyang-qian** [comment]
Thank you for your letter，I have fixed it. You can get the dataset now.

Recently, I was busy and did not notice that my storage service had expired.  Now I renew my storage service.

Please try again, could you now get the dataset?

Xiufeng Qian 













在 2022-07-01 01:30:06，"Xu Mingle" ***@***.***> 写道：

Hello,

Thank you for your interesting work and shared codes with dataset.

I try to check the dataset, but currently it is not available.

Could you please fix it?

Thank you inadvance.

**Comment by yangwill81** [comment]
The dataset is not available now. Could you please check it? Thanks~~

**Comment by haiyang-qian** [comment]
OK. I have fixed it.
















At 2022-10-25 00:30:24, "yangwill81" ***@***.***> wrote:

The dataset is not available now. Could you please check it? Thanks~~

**Comment by yangwill81** [comment]
Thanks for your dataset. I have another question that is how to use this dataset. Maybe can I only use the prepro_data or raw?

**Comment by kibitok** [comment]
Hello,
Great work.  
The dataset is not available. could you check it, please?

**Comment by haiyang-qian** [comment]
Hi，
thanks for your attention.
I just checked the link of the dataset and it is OK. Maybe you need to know how to use Baidu Cloud.










At 2023-01-14 00:17:22, "Kibitok" ***@***.***> wrote:

Hello,
Great work.
The dataset is not available. could you check it, please?
